### ISSUE TITLE
我们遇到了一个错误导致我们的应用闪退 

### ISSUE THREAD

**Issue by Fujimiya-Asuka** [woncan/device#1]
# WoncanThread(29696)

SIGSEGV(SEGV_MAPERR)

#00 pc 000000000001e274 /data/app/~~_pFTKeeP3JjN85MfOyAeEg==/com.-9mxZQIOosGX7fW1PkFJuQw==/base.apk (GnssCallback(WhitelistedMessage_struct*)+48)
2
#01 pc 000000000001c52c /data/app/~~_pFTKeeP3JjN85MfOyAeEg==/com.-9mxZQIOosGX7fW1PkFJuQw==/base.apk (AddWoncanDeviceData+236)
3
#02 pc 000000000001f784 /data/app/~~_pFTKeeP3JjN85MfOyAeEg==/com.-9mxZQIOosGX7fW1PkFJuQw==/base.apk (Java_com_woncan_device_JniImp_injectData+160)

**Comment by woncan** [comment]
硬件设备是什么型号
